/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "walhzhvjqkyxgttijkwc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbGh6aHZqcWt5eGd0dGlqa3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTEwMjksImV4cCI6MjA3MjY2NzAyOX0.l803-zboILB5IGmiw5UiJ49oXRyXSqOMxVQX9YR-SKg"